# Generated by Django 5.2.5 on 2026-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_description_useraddressmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
