# Generated by Django 5.2.5 on 2026-08-18 15:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_alter_useraddressmodel_description'),
        ('shop', '0004_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام گیرنده')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی گیرنده')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('state', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('shipping_address', models.CharField(max_length=300, verbose_name='آدرس ارسال')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کالاها')),
                ('shipping_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('final_price', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('refunded', 'مبلغ بازگردانده شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.useraddressmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
