# Generated by Django 5.2.5 on 2026-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('tipax', 'ارسال با تیپاکس'), ('pickup', 'دریافت حضوری')], default='tipax', max_length=20, verbose_name='روش دریافت'),
        ),
    ]
