# Generated by Django 5.2.5 on 2026-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مالیات'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percent',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='درصد مالیات'),
        ),
    ]
